# Generated by Django 3.1.7 on 2021-02-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210220_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=4, height_field=200, upload_to='main.html', width_field=100),
            preserve_default=False,
        ),
    ]
